### ISSUE TITLE
Warning about 'validation_depth'

### ISSUE THREAD

**Issue by kadaan** [mindsers/changelog-reader-action#41]
With the following config and a CHANGELOG.md that only has an `[Unreleased]` section, I get this warning: `Warning: Unexpected input(s) 'validation_depth', valid inputs are ['path', 'version']`

### Config
```
      - name: Validate changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          validation_depth: 10
          version: Unreleased
```
