### ISSUE TITLE
[Question] Finding a CHANGELOG.md dynamically? 

### ISSUE THREAD

**Issue by dep** [mindsers/changelog-reader-action#55]
I have a workflow that is triggered when new tags are created, and I don't always know the path to the CHANGELOG.md file. I'm trying to accomplish something like this:

```
- name: Get path for changelog
  id: changelog_path
  shell: bash
  run: |
    echo ::set-output name=path::$(ls ./**/${{ steps.app_short_name.outputs.name }}/CHANGELOG.md)
- name: Extract changelog
  if: ${{ steps.app_short_name.outputs.name && steps.check.outputs.result != 'stop' }}
  id: changelog_reader
  uses: mindsers/changelog-reader-action@v1
  with:
    version: steps.tag_version.outputs.current_version
    path: steps.changelog_path.outputs.path
```

Sadly this seems to fail, even though the path it's searching for returns a valid changelog. But maybe I'm going about this the wrong way. Any help is appreciated!

**Comment by dep** [comment]
Got it working. My `ls` pattern wasn't `bash` friendly.

```
- name: Get path for changelog
  if: ${{ steps.app_short_name.outputs.name && steps.check.outputs.result != 'stop' }}
  id: changelog_path
  shell: bash
  run: |
    find . -type f -path '*${{ steps.app_short_name.outputs.name }}*/*' -name 'CHANGELOG.md'
    echo ::set-output name=PATH::$(find . -type f -path '*${{ steps.app_short_name.outputs.name }}*/*' -name 'CHANGELOG.md')
- name: Extract changelog
  if: ${{ steps.app_short_name.outputs.name && steps.check.outputs.result != 'stop' }}
  id: changelog_reader
  uses: mindsers/changelog-reader-action@v1
  with:
    version: steps.tag_version.outputs.current_version
    path: ${{ steps.changelog_path.outputs.PATH }}
```
